language: generic
# The Travis Python version is unrelated to the version we build and test
# with.  This is set with the MB_PYTHON_VERSION variable. 
# python: 3.5
dist: trusty
services: docker

os:
    - linux
    - osx

env:
    global:
        - PLAT=x86_64
        - MB_PYTHON_OSX_VER=10.9
        - PROJECT_SPEC="pyahocorasick pyahocorasick==1.4.0 lxml lxml==4.2.1 simplejson simplejson==3.15.0 intbitset intbitset==2.3.0 bitarray bitarray==0.8.1 pycryptodome pycryptodome==3.6.1 rdflib rdflib==4.2.1 urlpy scandir scandir==1.9.0 MarkupSafe MarkupSafe==1.0 coverage==4.4.1 coverage pdfminer.six pdfminer.six==20181108 pefile pefile==2018.8.8 pyyaml PyYAML==3.12 SPARQLWrapper SPARQLWrapper==1.8.0 psutil psutil==5.6.2 tinyarray cdifflib edlib hyperscan pyroaring"

    matrix:
        - MB_PYTHON_VERSION=2.7 UNICODE_WIDTH=16 
        - MB_PYTHON_VERSION=2.7 UNICODE_WIDTH=32 
        - MB_PYTHON_VERSION=3.6 UNICODE_WIDTH=32 
        - MB_PYTHON_VERSION=3.7 UNICODE_WIDTH=32 
        - MB_PYTHON_VERSION=3.8 UNICODE_WIDTH=32 
        - MB_PYTHON_VERSION=3.9 UNICODE_WIDTH=32

#matrix:
#  exclude:
#    # Exclude the default Python 3.5 build
#    - python: '3.5'

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - ls -al ${TRAVIS_BUILD_DIR}/wheelhouse/

script:
    - for whl in $PROJECT_SPEC; do build_index_wheel "$whl" || continue; done
    - ls -al ${TRAVIS_BUILD_DIR}/wheelhouse/

deploy:
  provider: bintray
  skip_cleanup: true
  file: bintray_travis.json
  user: pombreda
  key:
    secure: l8uNfriu2L+rHRRBsR8R6pGHFt+r1Rymfk+1pOKdJTR8NjgBAYEAxPU6IPr+drH1WheXGVFoWttWTcplvo8Xmc+skUMXKUnjNCgrRE0rYKqjdHmEBMKUAjAfZ3hq48ayjRm3FvAjPwcWbTD0siBjK1qm4SD7TBEEC28XuJhT1oE=

