environment:
  global:
    WHEELS: |
        pyahocorasick==1.4.0
        lxml
        lxml==4.2.1
        simplejson
        simplejson==3.15.0
        intbitset
        intbitset==2.3.0
        bitarray
        bitarray==0.8.1
        pycryptodome
        pycryptodome==3.6.1
        rdflib
        rdflib==4.2.1
        urlpy
        scandir
        scandir==1.9.0
        MarkupSafe
        MarkupSafe==1.0
        coverage 
        coverage==4.4.1
        pdfminer.six
        pdfminer.six==20181108
        pefile
        pefile==2018.8.8
        pyyaml
        PyYAML==3.12
        SPARQLWrapper
        SPARQLWrapper==1.8.0
        psutil
        psutil==5.6.2
        tinyarray
        cdifflib
        edlib
        hyperscan
        pyroaring

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip wheel
  - mkdir wheelhouse

# use test step instead
build: false

test_script:
  - python -m pip wheel --wheel-dir=wheelhouse url || dir
  - for /F "delims= " %%I in (%WHEELS%) do (
    python -m pip wheel --wheel-dir=wheelhouse %%I || dir)
  - dir /S /B

artifacts:
  - path: wheelhouse\*

deploy:
  - provider: BinTray
    username: pombreda
    version: "1"
    override: true
    api_key:
      secure: vfOXPuSdGaUBQWCWhtXGWOKFoWulmg8dl3J8EP7RodmMN96VH8yeMQIHdU3f4+l/
    subject: pombreda
    repo: thirdparty2
    package: thirdparty2
    publish: true
